parent(john,ann).
parent(papa,john).
parent(papa,jim).
parent(jim,john).
parent(jim,keith).
parent(mary,ann).
parent(mary,sylvia).
parent(brian,sylvia).
male(jim).
male(papa).
female(sylvia).
female(ann).
male(brian).
male(john).
male(keith).
brother(X,Y):-parent(Z,X),parent(Z,Y),male(X),X\=Y.
uncle(X,Y):-
male(X),brother(X,Z),parent(Z,Y).