parent(john,ann).
parent(jim,john).
parent(jim,keith).
parent(mary,ann).
parent(mary,sylvia).
parent(brian,sylvia).
male(keith).
male(jim).
female(sylvia).
female(ann).
male(brian).
sister(X,Y):-
female(X),parent(Z,Y),parent(Z,X),(X\=Y).
brother(X,Y):-
male(X),parent(Z,X),parent(Z,Y),(X\=Y).
uncle(X,Y):-
male(X),parent(R,Y),(brother(X,R);sister(R,X)).
halfsister(X,Y):-
female(X),female(Y),parent(R,X),parent(R,Y),parent(Z,X),parent(Q,Y),(Z\=Q),(Z\=R),(Q\=R).